### ISSUE TITLE
[QAIT] [Prestashop (1.7.1.1)] Bankwire icon is appearing instead of Oxipay logo under Payment for Prestashop.

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-prestashop-1.6#14]
**Pre requisite:** 
1) Login to Prestashop Admin: http://115.113.54.81/prestashop/admin205cdfcen (ramaanjeetsingh@qainfotech.com / Qait@12345)
2) Navigate to Payment Methods and then Installed Modules.
3) Click on 'Configure' for Oxipay and delete the 'Logo' if its already there (if its not let the logo be blank)
4) Save the changes.

**Steps to Replicate:**
1. Launch URL: http://115.113.54.81/prestashop
2. Add any item to cart and enter valid address.
3. Checkout and verify that a 'bankwire' icon is appearing against 'Oxipay'instead of Oxipay icon under the Payment.

**Acceptance Criteria** : Plugin should provide a default Oxipay icon.

Screen Cast: https://www.screencast.com/t/dZCzduv6Td
Shared Document: http://docs.oxipay.com.au/platforms/prestashop/

**Test Case**
#41 : Verify that correct logo of Oxipay is displayed to end user on payment page

Issue reproducible for below
Tech Stack Details:
 - Ubuntu (16.04 LTS) 
 - PHP version:(5.6.30)
 - mysql: (14.14)
 - Apache: (2.4.18)
Prestashop (1.7.1.1)
Oxipay_Prestashop 1.0.10

Issue Not reproducible on below tech-stack
Ubuntu (16.04 LTS) 
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)
prestashop_1.6.1.13
Oxipay_PrestashopV1.0.10

**Comment by blueninja2** [comment]
We would prefer the Oxipay icon to be hardcoded with a logo we would supply; however, we would appreciate Terem's thoughts on this.

**Comment by hellotaotao** [comment]
closing as this refers to the 'old' plugin.
