### ISSUE TITLE
[QAIT] [Prestashop (1.7.1.1)] User redirects to blank page while paying using OXIPAY.

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-prestashop-1.6#15]
**Steps to Replicate:**
1. Launch URL: http://115.113.54.81/prestashop
2. Add any item to cart and enter valid address.
3. Select OXIPAY as payment method and click on 'ORDER WITH AN OBLIGATION TO PAY' button.
4. Verify

**Actual Result:** User is navigated to blank page having url 'http://115.113.54.81/prestashop/module/oxipayprestashop/validation'.

**Acceptance Criteria:** User should navigate to OXIPAY login page.

**Screen Cast:** https://www.screencast.com/t/daGfWNpSb6VB
**Shared Document:** http://docs.oxipay.com.au/platforms/prestashop/

**Test Case:** Verify that user is able to make payment with AU and NZ payment gateways based on in which country they are doing transaction.

**Issue reproducible for below Tech Stack Details:**
Ubuntu (16.04 LTS) 
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)
Prestashop (1.7.1.1)
Oxipay_Prestashop 1.0.10

**Note:** Issue is not reproducible on below Tech stack

Ubuntu (16.04 LTS) 
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)
prestashop_1.6.1.13
Oxipay_PrestashopV1.0.10

**Comment by hellotaotao** [comment]
Confirmed. The plugin is totally not ready for 1.7
