### ISSUE TITLE
 [QAIT]  Payment is getting rejected on merchant site while using payment method as 'OXIPAY'.

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-prestashop-1.6#16]
**Observation:** 

1) User is getting navigated to url 'http://115.113.54.81/presta/prestashop/order?step=3&error_oxipay=1'.
2) Cart remains active.
3) Inventory doesn't get affected.
4) Order details are not getting generated under 'Order History'.

**Steps to Replicate:**

1. Launch URL: http://115.113.54.81/presta/prestashop
2. Add any item to cart and enter valid address.
3. Select OXIPAY as payment method and click on 'ORDER WITH AN OBLIGATION TO PAY' button.
4. Login into oxipay with valid credentials.
5. Enter card details and click on confirm button.
6. verify that oxipay approved page is displayed.
7. Now user is getting redirected to Payment Method page.
8. Verify

**Actual Result:** Payment is getting rejected on merchant site & displays error message 'The Payment provider rejected the transaction. Please try again.' while using payment method as 'OXIPAY'.

**Acceptance Criteria:** Payment should get approved on merchant site when user use 'OXIPAY' as payment method.

**Screen Cast:** https://www.screencast.com/t/vnw34Mo7qak 
**Shared Document:** http://docs.oxipay.com.au/platforms/prestashop/

**Test Case:** Verify that when payment is successful in Oxipay, payment gets completed in the merchant store

**Tech Stack Details:**
Ubuntu (16.04 LTS) 
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)
prestashop_1.6.1.13
Oxipay_PrestashopV1.0.10

Not able to verify for below tech stack due to bug #15 
Ubuntu (16.04 LTS) 
PHP version:(5.6.30)
mysql: (14.14)
Apache: (2.4.18)
Prestashop (1.7.1.1)
Oxipay_Prestashop 1.0.10

**Comment by blueninja2** [comment]
@ramanjeetaulakh-qait Can QA Info Tech please re-test this scenario as the flow didn't look okay. The tester logged in initially, then typed in their CC details and then was prompted to log in.
We can't work out how this could occur and so are you able to replicate?

This could have been a simple flaw in the sandbox environment at the time.
