### ISSUE TITLE
The AsyncCallback does not work in Terem's version (while it was working in the old version)

### ISSUE THREAD

**Issue by hellotaotao** [oxipay/oxipay-prestashop-1.6#18]
As a known issue which is also affecting other platforms like WooCommerce, when Prestashop "Friendly URL" setting (in Preference -> SEO&URLs) is set to false, the page redirect after completion is going to fail. However, in the previous version, as the AsyncCallback still works, the order status will be correctly updated anyway.
But in this version, the order status will fail to update in this case, which indicates that the Async-callback is not working. 

When "Friendly URL" is set to true, the order status will be correctly updated, as the result of successful page redirect.

**Comment by jmcmanamey-terem** [comment]
@am-oxipay were you able to locate the logs for this issue?

**Comment by hellotaotao** [comment]
As far as we can tell this is related to the sandbox environment.
