### ISSUE TITLE
[QAIT] Error message is displayed "An error occurred. Please contact the merchant to have more information." on clicking 'Return to cart' button from decline page

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-prestashop-1.6#19]
Steps to Reproduce:

1. Launch URL: http://ec2-54-252-200-135.ap-southeast-2.compute.amazonaws.com
2. Add any item to cart greater than '670' and enter a valid address.
3. Select OXIPAY as a payment method.
4. Login into oxipay with valid credentials.
5. Enter card details and click on confirm button.
6. Verify that decline message appears on clicking on 'Return to cart' option.

Actual Result: Error message is displayed "An error occurred. Please contact the merchant to have more information" on clicking 'Return to cart' button.

Acceptance Criteria:  It should navigate user to cart page with previosuly products added to cart.

Screen Cast: https://www.screencast.com/t/mGAF8wm6TO

Tech Stack Details:
http://ec2-54-252-200-135.ap-southeast-2.compute.amazonaws.com
http://ec2-54-252-200-135.ap-southeast-2.compute.amazonaws.com/administration

**Comment by hellotaotao** [comment]
I have made the following modifications to the acceptance criteria; other than that, this report appears accurate. 

Acceptance Criteria: 
* The user must be informed that the payment was declined. 
* It should navigate user to cart page with previously products added to cart if possible.

**Comment by am-oxipay** [comment]
For the declined message please use: "Payment has been declined by provider Oxipay" 

In terms of which page to land on i think this will depend slightly on how the system is configured: 
If the  "one page checkout" is enabled i believe it should place the customer on the 
"/quick-order" page.
If the standard "5 steps checkout" is enabled i think it should land on the 
"/order" page

Please let me know if this seems incorrect.
