### ISSUE TITLE
[QAIT] Oxipay confirmation email contains ‘Order ID #’ instead of ‘Order Reference #’ 

### ISSUE THREAD

**Issue by Piyush-Qait** [oxipay/oxipay-prestashop-1.6#20]
**Observation:**
‘Order ID #’ that is in email is different from Order ID # generated in Prestashop admin panel
‘Order Reference #’ is only visible to end user

**User Impact:** 
When the end user receives Oxipay email containing ‘Order ID #’, she/he might get confused with ‘Order ID’ as ‘Order Reference #’ is generated for an end user and ‘Order ID #’ is not displayed anywhere at the user end. 

**Steps to Replicate:**
Launch URL: http://ec2-54-252-200-135.ap-southeast-2.compute.amazonaws.com
Add any item to cart and enter a valid address.
Select OXIPAY as payment method
Login into oxipay with valid credentials.
Enter card details and click on confirm button.
Verify that oxipay approved page is displayed.
Verify that user received as Oxipay confirmation email.
Verify the result

**Actual Result:** Application contains ‘Order ID #’ instead of ‘Order Reference #’ in email which is received from Oxipay
**Acceptance Criteria:** Application should contain ‘Order Reference #’ in Oxipay confirmation email as ‘Order Reference #’ is only visible to end user

**Screencast:** https://www.screencast.com/t/pKNZkKZC 

**Tech Stack Details:**
http://ec2-54-252-200-135.ap-southeast-2.compute.amazonaws.com 
http://ec2-54-252-200-135.ap-southeast-2.compute.amazonaws.com/administration
 
**Username/Password**
user@example.com/bitnami

**Comment by am-oxipay** [comment]
This issue is going to be addressed by adding the Oxipay reference Id into the email, rather than the orderId as this conceptually makes more sense.
